---
output:
  html_document:
    toc: true
    toc_float: true
---

<style type="text/css">

body {
   font-size: 15px;
}

</style>

<br>
<br>

## Academic History

I received by undergraduate degree in psychology from the University of Colorado at Boulder in 2017 where I also received a certificate of public health. I'm often asked how I made the transition from psychology to biostatistics and data science. I was fortunate to be a part of a psychology program at CU that placed a lot of emphasis on research. This is how I first got my feet wet with statistics and R. From there, messing around with R became a hobby and ultimately pushed me down the biostatistics path. 

During August of 2017, I moved from Boulder to New York City to start an MPH in biostatistics at Columbia University. Since arriving at Columbia, I have worked on research projects analyzing trends of marijuana use and the effects of medical marijuana and recreational marijuana policy on substance abuse. I'm also a teaching assistant for an introductory biostatistics and epidemiology course where I lead a weekly lab section of 25 first year MPH students. 

### Relevant coursework 

• Probability Theory – Fall 2018  
• Data Science I – Fall 2018  
• Applied Regression II – Fall 2018  
• Relational Databases and SQL Programming – Fall 2018  
• Statistical Computing with SAS – Spring 2018  
• Applied Regression I – Spring 2018  
• Analysis of Categorical Data – Spring 2018  
• Research Methods and Applications – Fall 2017  
• Topics in Writing Science – Spring 2017  
• Introduction to Epidemiology – Spring 2017  
• Behavioral Genetics – Fall 2016  
• Research Methods in Psychology – Fall 2016  
• Psychological Statistics – Spring 2016  
• Intro to Probability and Statistics II – Spring 2015  
• Intro to Probability and Statistics I – Fall 2015  
• Calculus & Analytic Geometry II – Spring 2014  
• Calculus & Analytic Geometry I – Fall 2014  

## Professional Experience

*Columbia University Mailman School of Public Health, New York, NY	2018  
Biostatistics Intern, Advisor: Christine Mauro, PhD*

- Difference-in-difference analysis comparing tobacco use, cigarette use, and alcohol use among differing age groups before and after states pass recreational marijuana laws  

    - Analyses conducted in R by creating a shiny application which can be viewed/used at:                                          https://nicholaswilliams.shinyapps.io/mj_app_version2/  
    - Code is available on GitHub  
    
- Conducted analysis of the effect of medical marijuana law restrictiveness on prevalence change in past month use of           marijuana, past year use of marijuana, and first use of marijuana comparing after to before states passed medical marijuana   laws  

    - Analyses conducted in SAS using linear mixed-effects models  
    -	Code is available on GitHub  
    
- Analysis of CDC Multiple Cause of Death files to estimate corrected mortality rates and counts of death due to opioid         overdose  

    -	Analyses conducted in SAS and R using probit/logistic regression, SVM, and various other statistical/machine learning         methods  
    -	Code is available on GitHub








