---
title: "Plotly is fun"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar: 
      - { title: "Home", href: index.html, align: left }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```

```{r data import and cleaning}
# importing and cleaning a sample of size 5000 from the insta-cart dataset
insta_data <- p8105.datasets::instacart %>% 
  sample_n(5000) %>% 
  janitor::clean_names() %>% 
  mutate(order_id = as.factor(order_id), 
         order_dow = order_dow + 1)

# changing up the factoring of order day for plotting
days <- c("Sunday",
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday")

insta_data$order_dow <- days[insta_data$order_dow]

insta_data$order_dow <- fct_relevel(insta_data$order_dow,
                                    "Sunday",
                                    "Monday",
                                    "Tuesday",
                                    "Wednesday",
                                    "Thursday",
                                    "Friday",
                                    "Saturday")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Number of orders per department

```{r barchart, dpi = 300}
# for plotly you have to create lists for the axis labels... dumb
x_lab <- list(
  title = "Department"
  )

y_lab <- list(
  title = "Number of Orders"
  )

# bar chart of number of orders per department
insta_data %>% 
  group_by(department) %>% 
  summarize(numb_orders = n()) %>% 
  mutate(department = as.factor(department), 
        department = fct_reorder(department, numb_orders)) %>% 
  plot_ly(x = ~department, y = ~numb_orders, color = ~department, type = "bar") %>% 
  layout(xaxis = x_lab, 
         yaxis = y_lab)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Distribution of time at which orders are placed

```{r density plot, dpi = 300}
# density plot of order time stratified by order day
density_ggplotly <- insta_data %>%
  ggplot(aes(x = order_hour_of_day, fill = order_dow)) +
  geom_density(alpha = 0.2) +
  theme_bw() +
  labs(x = "Order hour of the day (24hr)", 
       y = "Denstiy") + 
  viridis::scale_fill_viridis(discrete = TRUE) + 
  guides(fill = guide_legend(title = "Day"))

ggplotly(density_ggplotly)
```

### Boxplots of time of order stratified by department

```{r boxplot, dpi = 300, fig.asp = "70%"}
# boxplots of order time stratified by the product department
box_ggplotly <- insta_data %>%  
  ggplot(aes(x = department, y = order_hour_of_day, fill = department)) + 
  geom_boxplot() + 
  coord_flip() +
  theme_bw() + 
  viridis::scale_fill_viridis(discrete = TRUE) + 
  labs(y = "Order hour of the day (24hr)",
       x = "Department") + 
  theme(legend.position = "none") 

ggplotly(box_ggplotly)
```

